#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pooja.Resource", IsApplication=true)]

namespace Pooja
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ganesha1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Ganesha2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Ganesha3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Ganesha4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Ganesha5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Ganesha6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Ganesha7 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int lblMessage = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int myButton = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int tableLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tableRow1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int tableRow2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tableRow3 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int main_lblMessage = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
